services:
  db:
    image: postgres:17-alpine
    container_name: library-db
    environment:
      - POSTGRES_USER=${LIBAPP_DB_USER}
      - POSTGRES_PASSWORD=${LIBAPP_DB_PASSWORD}
      - POSTGRES_DB=${LIBAPP_DB_NAME}
    volumes:
      - ${DATABASE_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LIBAPP_DB_USER} -d ${LIBAPP_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    environment:
      - LIBAPP_DB_HOST=db
      - LIBAPP_DB_USER=${LIBAPP_DB_USER}
      - LIBAPP_DB_PASSWORD=${LIBAPP_DB_PASSWORD}
      - LIBAPP_DB_NAME=${LIBAPP_DB_NAME}
      - LIBAPP_DATABASE_URL=host=db port=5432 user=${LIBAPP_DB_USER} password=${LIBAPP_DB_PASSWORD} dbname=${LIBAPP_DB_NAME} sslmode=disable
      - PORT=8080
      - LIBAPP_DIR_BACKUP=/app/backup
      - LIBAPP_DIR_APK=/app/apk
    ports:
      - "9092:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${SERVER_BOOKSTORAGE_FOLDER}:/app/bookarch
      - ${SERVER_LOGS}:/app/logs
      - ${SERVER_TMP_FOLDER}:/app/tempfld
      - ${BACKUP_PATH}:/app/backup
      - ${APK_ENV_PATH}:/app/apk
      - ./config.toml:/app/config.toml:ro
