services:
  db:
    image: postgres:17-alpine
    container_name: library-db
    environment:
      - POSTGRES_USER=${LIBAPP_DB_USER}
      - POSTGRES_PASSWORD=${LIBAPP_DB_PASSWORD}
#<<<<<<< HEAD
#      - POSTGRES_DB=${LIBAPP_DB_NAME}
#=======
      - POSTGRES_DB=${LIBAPP_DB_NAME}
#>>>>>>> 83d03999b7856536a568e4831f1b22e51f9335cd
    volumes:
#      - ./db/scripts/init_db.sql:/docker-entrypoint-initdb.d/01-init_db.sql
      - ${DATABASE_PATH}:/var/lib/postgresql/data
    healthcheck:
#<<<<<<< HEAD
#      test: ["CMD-SHELL", "pg_isready -U ${LIBAPP_DB_USER} -d postgres"]
#=======
      test: ["CMD-SHELL", "pg_isready -U ${LIBAPP_DB_USER} -d ${LIBAPP_DB_NAME}"]
#>>>>>>> 83d03999b7856536a568e4831f1b22e51f9335cd
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    environment:
      - LIBAPP_DB_HOST=db
      - LIBAPP_DB_USER=${LIBAPP_DB_USER}
      - LIBAPP_DB_PASSWORD=${LIBAPP_DB_PASSWORD}
      - LIBAPP_DB_NAME=${LIBAPP_DB_NAME}
      - LIBAPP_DATABASE_URL=host=db port=5432 user=${LIBAPP_DB_USER} password=${LIBAPP_DB_PASSWORD} dbname=${LIBAPP_DB_NAME} sslmode=disable
      - PORT=8080
    ports:
      - "9092:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${SERVER_BOOKSTORAGE_FOLDER}:/bookarch
      - ${SERVER_LOGS}:/logs
      - ${SERVER_TMP_FOLDER}:/tempfld
      - ./config.toml:/app/config.toml:ro
