# Use the official Golang image to build the application
FROM golang:1.25-alpine AS builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY src/ ./src/

# Build the Go app
RUN go build -o main ./src/


FROM postgres:17-alpine

ENV POSTGRES_USER=library
ENV POSTGRES_PASSWORD=library_secret
ENV POSTGRES_DB=librarydb

COPY db/scripts/init_db.sql /docker-entrypoint-initdb.d/01-init_db.sql

RUN apk add --no-cache go ca-certificates bash

WORKDIR /app

COPY --from=builder /app/main .

COPY static/ ./static/
COPY templates/ ./templates/

COPY startup.sh ./
RUN chmod +x startup.sh

ENV PORT=8080
ENV DATABASE_URL=host=localhost port=5432 user=$POSTGRES_USER password=$POSTGRES_PASSWORD dbname=$POSTGRES_DB sslmode=disable
EXPOSE 5432 8080

CMD ["./startup.sh"]