services:
  db:
    image: postgres:17-alpine
    container_name: library-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db/scripts/init_db.sql:/docker-entrypoint-initdb.d/01-init_db.sql
      - ${DATABASE_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    environment:
      - DATABASE_URL=host=db port=5432 user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable
      - PORT=8080
    ports:
      - "9092:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /media/LinPart/bookarch/bookarch:/bookarch
      - /media/LinPart/bookarch/logs:/logs
      - /media/LinPart/bookarch/tmp:/tempfld
      - ./config.toml:/config.toml:ro
